var controllerData = [
    {
        "Model": "ECB-600",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 16,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 12,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECB-400",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 12,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 12,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECB-300",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 10,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 8,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECB-203",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 6,
            "AOCount": 0,
            "DOCount": 5,
            "UOCount": 3,
            "IntegralActuator": false,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECB-103",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 4,
            "AOCount": 0,
            "DOCount": 4,
            "UOCount": 2,
            "IntegralActuator": false,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECB-VAV",
        "Manufacturer": "Distech",
        "CommType": ["BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 4,
            "AOCount": 0,
            "DOCount": 4,
            "UOCount": 2,
            "IntegralActuator": true,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-600",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 16,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 12,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-400",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 12,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 12,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-300",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 10,
            "AOCount": 0,
            "DOCount": 0,
            "UOCount": 8,
            "IntegralActuator": false,
            "netStatCount": 12,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-203",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 6,
            "AOCount": 0,
            "DOCount": 5,
            "UOCount": 3,
            "IntegralActuator": false,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-103",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 4,
            "AOCount": 0,
            "DOCount": 4,
            "UOCount": 2,
            "IntegralActuator": false,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "ECL-VAV",
        "Manufacturer": "Distech",
        "CommType": ["Lon"],
        "IO": {
            "AICount": 0,
            "DICount": 0,
            "UICount": 4,
            "AOCount": 0,
            "DOCount": 4,
            "UOCount": 2,
            "IntegralActuator": true,
            "netStatCount": 4,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
    {
        "Model": "FX-PCG2621",
        "Manufacturer": "JCI",
        "CommType": ["N2", "BacnetMSTP"],
        "IO": {
            "AICount": 0,
            "DICount": 2,
            "UICount": 6,
            "AOCount": 2,
            "DOCount": 3,
            "UOCount": 4,
            "IntegralActuator": false,
            "netStatCount": 0,
        },
        "PurchasingInfo": {
            "ListPrice": 0,
            "LastUpdated": 0,
        },
    },
];